kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.21-alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - apk add --no-cache git
      - go mod download
      # Linux AMD64
      - GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/diff-linux-amd64 .
      # Linux ARM64
      - GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o dist/diff-linux-arm64 .
      # Windows AMD64
      - GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o dist/diff-windows-amd64.exe .
      # macOS AMD64
      - GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o dist/diff-darwin-amd64 .
      # macOS ARM64 (M1/M2)
      - GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o dist/diff-darwin-arm64 .
      # 显示构建结果
      - ls -la dist/
    when:
      event:
        - push
        - tag

  # 创建 GitHub Release（仅在 tag 时执行）
  - name: github-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/*
      title: Release ${DRONE_TAG}
      note: |
        ## Release ${DRONE_TAG}
        
        ### 下载链接
        - Linux AMD64: diff-linux-amd64
        - Linux ARM64: diff-linux-arm64  
        - Windows AMD64: diff-windows-amd64.exe
        - macOS AMD64: diff-darwin-amd64
        - macOS ARM64: diff-darwin-arm64
        
      draft: false
    # when:
    #   event:
    #     - tag

trigger:
  branch:
    - master
    - main
    - develop
  event:
    - push
    - tag
