kind: pipeline
type: docker
name: build-and-release

trigger:
  event:
    - tag

clone:
  depth: 1

variables:
  APP_NAME: diff-tool
  MAIN_GO_PATH: .main.go

matrix:
  include:
    - GOOS: linux
      GOARCH: amd64
    - GOOS: linux
      GOARCH: arm64
    - GOOS: windows
      GOARCH: amd64
    - GOOS: darwin
      GOARCH: amd64
    - GOOS: darwin
      GOARCH: arm64

steps:
  - name: build-binaries
    image: golang:1.21
    environment:
      CGO_ENABLED: 0
    commands:
      - echo "Building for ${GOOS}/${GOARCH}..."
      - mkdir -p dist
      - export BINARY_NAME="${APP_NAME}-${GOOS}-${GOARCH}"
      - |
        if [ "${GOOS}" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
      - go build -v -o "dist/${BINARY_NAME}" -ldflags="-s -w" "${MAIN_GO_PATH}"
      - ls -lh dist/

  - name: generate-checksums
    image: alpine/git
    commands:
      - cd dist
      - sha256sum * > sha256sums.txt
      - cat sha256sums.txt
    depends_on:
      - build-binaries
    when:
      status:
        - success

  - name: github-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/*
      title: ${DRONE_TAG}
      note: ./.github/release_notes.md
      checksum:
        - sha256
        - md5
      draft: false
      prerelease: false
    depends_on:
      - generate-checksums
    when:
      event:
        - tag
      status:
        - success