kind: pipeline
type: docker
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0

steps:
  - name: build-linux-amd64
    image: golang:1.21.4
    commands:
      - go build
  - name: upload
    image: minio/mc
    environment:
      DRONE_ACCESS_KEY:
        from_secret: drone_access_key
      DRONE_SECRET_KEY:
        from_secret: drone_secret_key
    commands:
      - mv ScanPT scanpt-linux-amd64
      - mc config host add minio http://192.168.0.10:8011 $DRONE_ACCESS_KEY $DRONE_SECRET_KEY&&mc cp scanpt-linux-amd64 minio/transmission-diff-tool
